version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
#  create_infrastructure: 
#      docker:
#        - image: amazon/aws-cli
#      steps:
#        - checkout
#        - run:
#            name: Create Cloudformation Stack
#            command: |
#              aws cloudformation deploy \
#                --template-file template.yml \
#                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
#               --region us-east-1
  configure_infrastructure: 
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - run:
            echo $mykey >> key.pem
        - run:
            chmod 400 key.pem
        - run:
            ssh -i key.pem ubuntu@3.80.182.148
        - run:
            name: install ansible
            command: |
              apk add --update ansible
        - run:
            name: run playbook
            command: |
              ansible-playbook -i inventory.yml main.yml --private-key key.pem
              
# Sequential workflow
workflows:
  # Name the workflo
  myWorkflow:
    jobs:
      #- create_infrastructure
      - configure_infrastructure
